Bookstore/Components/CartSummaryViewComponent.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;

namespace Bookstore.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Cart cart;
        public CartSummaryViewComponent(Cart cartService)
        {
            cart = cartService;
        }
        public IViewComponentResult Invoke()
        {
            return View(cart);
        }
    }
}

Bookstore/Components/CategoriesViewComponent.cs
using Bookstore.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Bookstore.Components
{
    public class CategoriesViewComponent : ViewComponent  //Inheret from ViewComponent class
    {
        //Create an instance of the repository
        private IBookstoreRepository repo { get; set; }

        //Constructor
        public CategoriesViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }

        //When this view component is invoked, return the following view along with the info
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedCategory = RouteData?.Values["categoryType"];  //Get any category types being passed in

            //Pull in each category from our database and pass it to the view
            var categories = repo.Books
                .Select(x => x.Category)
                .Distinct()
                .OrderBy(x => x);

            return View(categories);
        }
    }
}

Bookstore/Views/Shared/BookList.cshtml
@{
}
<!--Pass in the model-->
@model Book

<!--Put each book in a seperate css box-->
<div class="card card-outline-primary m-1 p-1 shadow">

    <!--Header-->
    <div class="card-header">
        <h3>"@Model.Title"</h3>
    </div>

    <!--Card body-->
    <div class="card-body">
        <div class="card-title">
            <h4>By: @Model.Author</h4>
        </div>

        <span class="badge badge-secondary" style="float:right">
            Price: $@Model.Price
        </span>
        <br />

        <div class="card-text">
            <ul style="list-style-type: none; font-size:medium">
                <li>Category: @Model.Category</li>
                <li>Publisher: @Model.Publisher</li>
                <li>Classification: @Model.Classification</li>
                <li>Page Count: @Model.PageCount</li>
                <li>Isbn: @Model.Isbn</li>
            </ul>
        </div>

        <!--Form for add to cart button-->
        <form method="post" asp-page="/Buy">
            <!--Send book id with the form-->
            <input type="hidden" asp-for="@Model.BookId" />

            <!--Pass info that will enable to return to this page later-->
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />

            <!--Submit button-->
            <span class="card-text">
                <button type="submit" class="btn btn-success btn-small float-end">Add to Cart</button>
            </span>
        </form>
    </div>

</div>

Bookstore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Bookstore</title>
    <link href="~/lib/css/bootstrap.min.css" rel="stylesheet" />
    <link href="/lib/font-awesome/css/all.min.css" rel="stylesheet" />
</head>
<body>
    <!--Css for page heading-->
    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col-6 navbar-brand">
                    BOOK LIST
                    <!--Connects to CartSummary View-->
                    <div class="col-6 float-right">
                        <vc:cart-summary />
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="row m-1 p-1">

        <!--Left column-->
        <div id="categories" class="col-3">
            <vc:categories></vc:categories>  <!--Connect to the CategoriesViewComponent-->
        </div>

        <!--Body text will take up 3/4 of the page-->
        <div class="col-9">
            <div>
                @RenderBody()
            </div>
        </div>
    </div>
</body>
</html>